<?php

return [
    'cms' => [
        'pages' => [
            'site' => [
                'label' => 'Site header & footer',
                'description' => 'Brand name, navigation, footer, shared pricing facts, and search defaults used across the public website.',
                'preview_url' => '/',
            ],
            'home' => [
                'label' => 'Home page',
                'description' => 'The main audio-to-text landing page, including its demo workspace and calls to action.',
                'preview_url' => '/',
            ],
            'audio_to_text' => [
                'label' => 'Audio to text',
                'description' => 'The focused audio-to-text SEO page, workflows, comparisons, guides, and FAQs.',
                'preview_url' => '/audio-to-text',
            ],
            'features' => [
                'label' => 'Features',
                'description' => 'Feature explanations, online-versus-desktop comparison, and feature FAQs.',
                'preview_url' => '/features',
            ],
            'pricing' => [
                'label' => 'Pricing page',
                'description' => 'Public pricing-page headings, labels, SEO, and FAQs. Actual rates remain in Pricing Manager.',
                'preview_url' => '/price',
            ],
            'download' => [
                'label' => 'Windows download',
                'description' => 'Windows download copy, release labels, requirements, models, and desktop FAQs.',
                'preview_url' => '/download',
            ],
            'blog' => [
                'label' => 'Blog landing & article layout',
                'description' => 'Blog landing copy and labels shared by every article. Article bodies remain in Blog Manager.',
                'preview_url' => '/blog',
            ],
        ],
    ],
    'pages' => [
        'site' => [
            'brand' => [
                'name' => 'JERVA Transcriber',
                'home_url' => '/',
            ],
            'navigation' => [
                'aria_label' => 'Main navigation',
                'mobile_open_label' => 'Open navigation',
                'items' => [
                    ['label' => 'Audio to text', 'url' => '/audio-to-text'],
                    ['label' => 'Features', 'url' => '/features'],
                    ['label' => 'Pricing', 'url' => '/price'],
                    ['label' => 'Blog', 'url' => '/blog'],
                    ['label' => 'Download', 'url' => '/download'],
                ],
                'sign_in_label' => 'Sign in',
                'sign_in_url' => '/login',
                'primary_button_label' => 'Get started',
                'primary_button_url' => '/register',
            ],
            'footer' => [
                'brand_body' => 'Convert audio to text online or use the free Windows app for local Whisper transcription, review, online cleanup, summaries, and exports.',
                'columns' => [
                    [
                        'title' => 'Product',
                        'links' => [
                            ['label' => 'Features', 'url' => '/features'],
                            ['label' => 'Audio to text', 'url' => '/audio-to-text'],
                            ['label' => 'Pricing', 'url' => '/price'],
                            ['label' => 'Desktop app', 'url' => '/download'],
                        ],
                    ],
                    [
                        'title' => 'Learn',
                        'links' => [
                            ['label' => 'Blog', 'url' => '/blog'],
                            ['label' => 'Sign in', 'url' => '/login'],
                            ['label' => 'Create account', 'url' => '/register'],
                        ],
                    ],
                ],
                'workspace_title' => 'Workspace',
                'workspace_body' => 'Use the online workspace for convenience or download the free desktop app for offline Whisper, VAD, and speaker separation.',
                'copyright' => 'Copyright {year} JERVA Transcriber. All rights reserved.',
            ],
            'pricing_proof' => [
                'aria_label' => 'JERVA pricing and product facts',
                'free_value_fallback' => 'Free',
                'free_minutes_suffix' => 'min',
                'free_active_label' => 'online every day',
                'free_fallback_label' => 'daily online allowance',
                'upload_value_fallback' => 'Pay as you go',
                'upload_active_label' => 'per uploaded audio hour',
                'upload_fallback_label' => 'for extra online use',
                'live_value_fallback' => 'No subscription',
                'live_active_label' => 'per live audio hour',
                'live_fallback_label' => 'required',
                'languages_value' => '99+',
                'languages_label' => 'Whisper languages',
                'desktop_value' => '$0',
                'desktop_label' => 'Windows desktop app',
            ],
            'seo' => [
                'site_name' => 'JERVA Transcriber',
                'default_image_url' => '/JervaLogo.png',
            ],
            'schema' => [
                'organization_name' => 'JERVA Transcriber',
                'website_name' => 'JERVA Transcriber',
                'home_breadcrumb_label' => 'Home',
                'application_name' => 'JERVA Transcriber',
                'application_category' => 'BusinessApplication',
                'application_operating_system' => 'Web browser, Windows',
                'offer_currency' => 'USD',
                'home_application_description' => 'Convert meetings, interviews, lectures, podcasts, and voice recordings into editable text online or offline on Windows.',
                'free_offer_fallback' => 'Free daily online transcription allowance',
                'free_offer_template' => '{minutes} online transcription minutes free each day',
                'home_feature_list' => [
                    'Online and offline audio-to-text transcription',
                    'Multilingual Whisper transcription',
                    'Voice activity detection',
                    'Speaker separation',
                    'Optional online transcript cleanup and summaries',
                    'TXT, Word, and Excel exports',
                ],
                'audio_application_name' => 'JERVA Audio to Text Converter',
                'audio_application_description' => 'Hosted audio-to-text transcription in a browser and local Whisper transcription in the JERVA Windows app.',
                'audio_feature_list' => [
                    'Uploaded and live audio transcription',
                    'Online and Windows offline processing modes',
                    'Long-recording progress and retry controls',
                    'Source-linked transcript review',
                    'TXT, Word-compatible, and Excel-compatible exports',
                ],
                'download_application_name' => 'JERVA Transcriber for Windows',
                'download_application_description' => 'Free offline Whisper transcription for Windows with local voice activity detection, local speaker separation, optional online text tools, and exports.',
                'download_feature_list' => [
                    'Offline Whisper transcription',
                    'Live recording and audio uploads',
                    'Silero voice activity detection',
                    'Speaker separation',
                    'Optional online transcript cleanup and summaries',
                    'TXT, Word, and Excel exports',
                ],
            ],
        ],
        'home' => [
            'seo' => [
                'title' => 'JERVA Transcriber | Audio to Text Online or Offline',
                'description' => 'Convert MP3, WAV, M4A, and other audio to text online or with JERVA\'s free Windows app. Review, polish, and export your transcript.',
            ],
            'hero' => [
                'eyebrow' => 'Audio to text for recordings and live speech',
                'title' => 'Convert audio to text online or offline',
                'intro' => 'Turn meetings, interviews, lectures, podcasts, and voice recordings into editable text. Use the browser workspace for hosted transcription, or download the free Windows app to run supported Whisper models on your own computer.',
                'online_button_label' => 'Convert audio to text',
                'online_button_url' => '/register',
                'desktop_button_label' => 'Download free for Windows',
                'desktop_button_url' => '/download',
                'note' => 'No required subscription. Use the free Windows app, the daily online allowance, or pay only for extra hosted processing.',
                'note_link_label' => 'See how audio-to-text conversion works.',
                'note_link_url' => '/audio-to-text',
            ],
            'workspace_preview' => [
                'aria_label' => 'JERVA workspace preview',
                'brand_name' => 'JERVA Transcriber',
                'workspace_label' => 'Web workspace',
                'add_transcript_label' => 'Add Transcript',
                'recent_label' => 'Recent',
                'recent_items' => ['Client intake call', 'Product standup', 'Lecture notes'],
                'transcript_label' => 'Transcript',
                'active_transcript_title' => 'Client intake call',
                'processing_label' => 'Transcribing',
                'sample_transcript' => [
                    'We need the final transcript cleaned, summarized, and exported before the review call.',
                    'Action items: send the revised scope, confirm file naming, and prepare the client-ready notes.',
                ],
                'actions' => ['Live', 'Upload Audio', 'Polish', 'Export'],
            ],
            'pricing_note' => [
                'text' => 'Need more than the daily allowance?',
                'link_label' => 'Compare online pricing',
                'link_url' => '/price',
            ],
            'paths_intro' => [
                'eyebrow' => 'Choose your workflow',
                'title' => 'Online convenience or free local processing',
                'body' => 'You do not have to force every recording through the same route. Pick the option that makes sense for the computer and audio in front of you.',
            ],
            'paths' => [
                [
                    'eyebrow' => 'Online',
                    'title' => 'Online audio-to-text workspace',
                    'body' => 'Upload a recording or capture live audio in a modern browser without installing a speech model. Hosted processing is the practical choice for lightweight computers or faster setup.',
                    'bullets' => ['Free minutes refresh daily', 'No subscription required', 'Pay only when you need more'],
                    'button_label' => 'Start online',
                    'button_url' => '/register',
                ],
                [
                    'eyebrow' => 'Windows',
                    'title' => 'Offline audio to text on your PC',
                    'body' => 'Download JERVA for free and run a supported multilingual Whisper model locally. After the app and model are installed, offline transcription does not require an account or internet connection.',
                    'bullets' => ['Free desktop app', 'Local audio processing', 'Tiny through Large v3 and Turbo models'],
                    'button_label' => 'Download the app',
                    'button_url' => '/download',
                ],
            ],
            'workflow' => [
                'title' => 'Convert audio to text in three steps',
                'intro' => 'The same practical workflow applies whether JERVA processes the recording through hosted services or on your Windows computer.',
                'steps' => [
                    ['title' => 'Record or upload audio', 'body' => 'Capture speech live or add an existing WAV, MP3, M4A, AAC, OGG, FLAC, or WebM recording.'],
                    ['title' => 'Transcribe it', 'body' => 'Choose hosted transcription for convenience or a supported local Whisper model for free offline processing on Windows.'],
                    ['title' => 'Review and export text', 'body' => 'Check the transcript against the recording, optionally polish or summarize it online, then export TXT, Word, or Excel-compatible files.'],
                ],
            ],
            'use_cases' => [
                'title' => 'Audio to text for the recordings you already have',
                'intro' => 'Use one review-focused workspace for speech captured at work, in class, during research, or while creating content.',
                'items' => [
                    ['title' => 'Meeting audio to text', 'body' => 'Create searchable first-draft notes from meetings, client calls, briefings, and project updates.'],
                    ['title' => 'Lecture and interview transcription', 'body' => 'Turn lectures, study sessions, and research interviews into text that is easier to review and quote carefully.'],
                    ['title' => 'Podcast and video source text', 'body' => 'Prepare transcript drafts, summaries, show-note source material, and text that can support captions after review.'],
                ],
            ],
            'vad' => [
                'eyebrow' => 'Smarter local processing',
                'title' => 'Skip quiet sections in the Windows app',
                'body' => 'In the desktop workflow, Silero Voice Activity Detection finds spoken sections and skips quiet ranges before local transcription. This keeps long pauses out of the Whisper workload.',
                'note' => 'VAD is a desktop feature. Speech detection results depend on the recording and selected settings.',
            ],
            'faq' => [
                ['question' => 'How do I convert an audio file to text with JERVA?', 'answer' => 'Create an account and upload the recording in the online workspace, or install the Windows app and select an offline Whisper model. JERVA splits longer recordings into manageable sections, produces a transcript, and keeps the text connected to review and export tools.'],
                ['question' => 'Is JERVA really free?', 'answer' => 'Yes. The Windows desktop app is free, and local Whisper transcription does not use paid online minutes. Online accounts also receive a free transcription allowance that refreshes daily.'],
                ['question' => 'Do I need a subscription?', 'answer' => 'No. There is no required monthly or yearly subscription. Use the free desktop workflow, the daily online allowance, or add pay-as-you-go credit when you need more online processing.'],
                ['question' => 'Does JERVA support 99+ languages?', 'answer' => 'JERVA’s multilingual Whisper-based offline workflow can recognize more than 99 languages. Accuracy is not identical in every language and can change with the model, accent, speakers, background noise, and recording quality.'],
                ['question' => 'Do I need a powerful computer?', 'answer' => 'Not necessarily. The desktop app offers several Whisper model sizes and CPU fallback. If local transcription is too slow for your hardware, you can sign in and switch to online processing.'],
                ['question' => 'Where are offline recordings processed?', 'answer' => 'When offline mode is selected, transcription runs on your Windows computer. Online features send the required audio or text to JERVA’s hosted services.'],
            ],
            'faq_heading' => [
                'title' => 'JERVA transcription FAQ',
            ],
            'cta' => [
                'title' => 'Turn your next audio recording into text',
                'body' => 'Start in the browser with an account, or download the free Windows app for local Whisper transcription.',
                'online_button_label' => 'Start converting online',
                'online_button_url' => '/register',
                'desktop_button_label' => 'Download for Windows',
                'desktop_button_url' => '/download',
            ],
            'schema' => [
                'breadcrumb_label' => 'Home',
            ],
        ],
        'audio_to_text' => [
            'seo' => [
                'title' => 'Audio to Text Converter Online & Offline | JERVA',
                'description' => 'Convert MP3, WAV, M4A, AAC, OGG, FLAC, and WebM audio to editable text online or locally on Windows. Review and export with JERVA.',
            ],
            'hero' => [
                'eyebrow' => 'Online and offline audio-to-text converter',
                'title' => 'Convert audio to text with JERVA',
                'intro' => 'Upload a recording or capture speech live, create an editable transcript, review it alongside the source audio, and export the result. Use hosted transcription in your browser or a supported local Whisper model in the free Windows app.',
                'primary_button_label' => 'Start online',
                'primary_button_url' => '/register',
                'secondary_button_label' => 'Download Windows app',
                'secondary_button_url' => '/download',
                'note' => 'The online workspace requires a JERVA account. Offline mode requires the Windows app and a downloaded Whisper model.',
                'formats' => ['MP3', 'WAV', 'M4A', 'AAC', 'OGG', 'FLAC', 'WebM'],
            ],
            'hero_preview' => [
                'title' => 'Add a recording',
                'subtitle' => 'Upload audio or capture speech live',
                'steps' => ['Upload or record', 'Transcribe in sections', 'Review and export'],
                'formats_label' => 'Supported common formats',
            ],
            'benefits' => [
                'title' => 'More than a block of generated text',
                'intro' => 'JERVA is built around the work that follows speech recognition: tracking long jobs, checking uncertain wording, and getting the transcript into a usable file.',
                'items' => [
                    ['title' => 'Long-audio workflow', 'body' => 'Long recordings are processed in sections so progress, retry, cancellation, and review remain manageable.'],
                    ['title' => 'Source-linked review', 'body' => 'Transcript sections stay connected to timing and available audio playback so names, numbers, and quotations can be checked.'],
                    ['title' => 'Online or local processing', 'body' => 'Use hosted providers from the browser, or keep transcription on a Windows PC by selecting an installed offline model.'],
                    ['title' => 'Useful exports', 'body' => 'Export raw or cleaned transcript text to TXT, Word-compatible, or Excel-compatible files for editing and reporting.'],
                ],
            ],
            'workflow' => [
                'title' => 'How the audio-to-text converter works',
                'intro' => 'There is no public anonymous upload: sign in for hosted processing or use the Windows app for the offline workflow.',
                'step_label' => 'Step',
                'steps' => [
                    ['title' => 'Add your audio', 'body' => 'Upload a supported recording or use live microphone capture. Clear speech and a consistent recording level give every transcription model a better starting point.'],
                    ['title' => 'Choose a processing mode', 'body' => 'Select online transcription for hosted processing, or offline transcription in the Windows app when you want a local Whisper workflow.'],
                    ['title' => 'Review, polish, and export', 'body' => 'Check the raw text first. Online tools can polish or summarize a transcript, while export options prepare the version you need.'],
                ],
            ],
            'use_cases' => [
                'title' => 'What can you turn into text?',
                'items' => [
                    ['title' => 'Meetings and calls', 'body' => 'Build reviewable notes from team meetings, consultations, briefings, and recorded calls.'],
                    ['title' => 'Interviews and research', 'body' => 'Create a first draft for qualitative interviews, field recordings, and source review.'],
                    ['title' => 'Lectures and study recordings', 'body' => 'Turn spoken lessons into searchable study material while keeping the recording available for verification.'],
                    ['title' => 'Podcasts and recorded content', 'body' => 'Prepare transcript drafts and source text for show notes, summaries, articles, and captions.'],
                ],
            ],
            'comparison' => [
                'title' => 'Online audio to text or offline on Windows?',
                'intro' => 'Both routes produce text in JERVA, but they have different setup, privacy, and hardware tradeoffs.',
                'label_column' => 'Compare',
                'online_column' => 'Online',
                'desktop_column' => 'Windows offline',
                'rows' => [
                    ['label' => 'Where transcription runs', 'online' => 'JERVA hosted services and configured providers', 'desktop' => 'On the Windows computer in offline mode'],
                    ['label' => 'Account', 'online' => 'Required', 'desktop' => 'Not required for offline transcription'],
                    ['label' => 'Internet', 'online' => 'Required', 'desktop' => 'Required for setup and model download, not for installed offline models'],
                    ['label' => 'Cost', 'online' => 'Free daily allowance, then configured pay-as-you-go rates', 'desktop' => 'Free local transcription; your computer supplies the processing'],
                    ['label' => 'Processing speed', 'online' => 'Depends on upload, queue, and provider availability', 'desktop' => 'Depends on model choice and PC resources'],
                ],
            ],
            'limitations' => [
                'title' => 'What JERVA does not promise',
                'body' => 'Automated audio transcription is a first draft, not a certified record. Results vary with language, accent, overlapping speakers, microphone distance, noise, compression, model, and provider.',
                'items' => [
                    'JERVA does not advertise a universal accuracy percentage.',
                    'Speaker labels are detected groups, not verified identities.',
                    'Names, figures, technical terms, and important quotations should be checked against the audio.',
                    'Polish and summaries can make text easier to use, but they can also change meaning and should be reviewed.',
                ],
            ],
            'guides' => [
                'title' => 'Audio-to-text guides',
                'read_label' => 'Read guide',
                'items' => [
                    ['title' => 'How to convert audio to text', 'url' => '/blog/how-to-convert-audio-to-text'],
                    ['title' => 'How to convert MP3 to text', 'url' => '/blog/how-to-convert-mp3-to-text'],
                    ['title' => 'Improve transcription accuracy', 'url' => '/blog/improve-audio-transcription-accuracy'],
                ],
            ],
            'faq' => [
                ['question' => 'Which audio files can I convert to text?', 'answer' => 'The JERVA interfaces accept common audio formats including MP3, WAV, M4A, AAC, OGG, FLAC, and WebM. A file still needs to contain decodable audio, and browser or server limits can apply to very large uploads.'],
                ['question' => 'Can I convert audio to text for free?', 'answer' => 'Yes. Online accounts receive the currently configured free daily allowance. The Windows app and its offline transcription workflow are free after you install a supported local model.'],
                ['question' => 'Can JERVA transcribe a one-hour recording?', 'answer' => 'JERVA is designed to split longer uploads into sections and show processing progress. Actual completion time depends on upload speed, queue load, provider availability, selected model, computer resources, and the recording itself.'],
                ['question' => 'Is audio-to-text transcription completely accurate?', 'answer' => 'No automatic transcription system is completely accurate for every recording. Review names, numbers, specialist vocabulary, speaker changes, and any wording that will be quoted or relied upon.'],
                ['question' => 'Can JERVA identify different speakers?', 'answer' => 'The Windows workflow can use local speaker diarization to group detected voices. Overlap, noise, similar voices, and microphone conditions can produce incorrect labels, and JERVA does not automatically know each person\'s name.'],
                ['question' => 'Does offline mode send my audio to a server?', 'answer' => 'When offline transcription is selected and a supported model is installed, speech recognition runs on the Windows computer. Online transcription, polish, summaries, account services, model downloads, and updates require network access.'],
            ],
            'faq_heading' => [
                'title' => 'Audio-to-text FAQ',
            ],
            'cta' => [
                'title' => 'Ready to turn audio into editable text?',
                'body' => 'Create an account for the browser workspace or download JERVA for a local Windows transcription option.',
                'primary_button_label' => 'Create an account',
                'primary_button_url' => '/register',
                'secondary_button_label' => 'Download for Windows',
                'secondary_button_url' => '/download',
            ],
            'schema' => [
                'breadcrumb_label' => 'Audio to Text',
            ],
        ],
        'blog' => [
            'seo' => [
                'title' => 'Audio to Text & Transcription Guides | JERVA Blog',
                'description' => 'Practical guides for converting audio to text, transcribing meetings and interviews, improving recordings, reviewing transcripts, and choosing online or offline tools.',
            ],
            'hero' => [
                'eyebrow' => 'Audio-to-text guides',
                'title' => 'Practical transcription guides for real recordings',
                'intro' => 'Learn how to turn audio into useful text, prepare clearer source recordings, review machine-generated transcripts, and choose between hosted and local processing.',
            ],
            'topics' => [
                'Audio to text',
                'MP3 and recording formats',
                'Meeting and interview transcription',
                'Transcript review and accuracy',
                'Online vs. offline processing',
            ],
            'index' => [
                'featured_label' => 'Start here',
                'reading_time_template' => '{minutes} min read',
                'read_label' => 'Read the guide',
                'empty_title' => 'Guides are being prepared',
                'empty_body' => 'No published transcription guides are available yet. Please check back soon.',
            ],
            'article' => [
                'breadcrumb_aria_label' => 'Breadcrumb',
                'home_label' => 'Home',
                'home_url' => '/',
                'blog_label' => 'Blog',
                'blog_url' => '/blog',
                'reading_time_template' => '{minutes} min read',
                'byline' => 'By JERVA Transcriber',
                'review_title' => 'Review important transcripts.',
                'review_body' => 'Automatic speech recognition can mishear names, numbers, technical terms, accented speech, and overlapping speakers. Check any wording you will quote, publish, or rely upon against the source audio.',
                'all_guides_label' => 'All transcription guides',
                'all_guides_url' => '/blog',
                'last_updated_label' => 'Last updated',
                'related_title' => 'Related audio-to-text guides',
                'related_read_label' => 'Read guide',
                'seo_title_template' => '{title} | JERVA',
            ],
            'cta' => [
                'title' => 'Need to turn a recording into text?',
                'body' => 'See the online and Windows workflows, supported formats, practical limits, and export options.',
                'button_label' => 'Explore audio to text',
                'button_url' => '/audio-to-text',
            ],
            'article_cta' => [
                'title' => 'Convert your own audio to text',
                'body' => 'Compare JERVA\'s hosted browser workflow with its free local Windows transcription option.',
                'button_label' => 'See audio-to-text options',
                'button_url' => '/audio-to-text',
            ],
            'schema' => [
                'breadcrumb_label' => 'Blog',
            ],
        ],
        'pricing' => [
            'seo' => [
                'title' => 'Affordable Pay-As-You-Go Transcription Pricing | JERVA',
                'description' => 'Compare JERVA online transcription rates, free daily minutes, and pay-as-you-go credits. No monthly or yearly subscription is required.',
            ],
            'hero' => [
                'eyebrow' => 'Pricing',
                'title' => 'Use JERVA Transcriber as you go',
                'intro' => 'Every JERVA Transcriber account gets a free transcription allowance each day. Buy extra credits only when a busy day needs more.',
            ],
            'plans_ui' => [
                'popular_label' => 'Popular',
                'audio_upload_label' => 'Audio Upload:',
                'live_recording_label' => 'Live Recording:',
                'polishing_label' => 'Polishing:',
                'summarization_label' => 'Summarization:',
                'per_hour_suffix' => '/hour',
                'per_thousand_characters_suffix' => '/1K chars',
                'button_url' => '/register',
            ],
            'comparison' => [
                'title' => 'Compare credit packs',
                'feature_column_label' => 'Feature',
                'included_label' => 'Included',
                'not_included_label' => 'Not included',
                'not_included_symbol' => '—',
            ],
            'faq' => [
                ['question' => 'Can I use JERVA Transcriber offline?', 'answer' => 'Yes. The free Windows app can run Whisper locally after you download a model. The browser workspace uses online processing.'],
                ['question' => 'Is there recurring billing?', 'answer' => 'No. JERVA Transcriber uses a free daily allowance and pay-as-you-go credits instead of required monthly or yearly billing.'],
                ['question' => 'What happens when I reach my free minutes?', 'answer' => 'Your free allowance refreshes the next day, or you can buy credit to keep using online transcription immediately.'],
            ],
            'faq_heading' => [
                'title' => 'Pricing FAQ',
            ],
            'schema' => [
                'breadcrumb_label' => 'Pricing',
            ],
        ],
        'features' => [
            'seo' => [
                'title' => 'Audio to Text Features: Online & Offline | JERVA',
                'description' => 'Explore JERVA audio-to-text features: browser and offline Windows transcription, long-audio progress, speaker grouping, review, polish, summaries, and exports.',
            ],
            'hero' => [
                'eyebrow' => 'Features',
                'title' => 'Audio-to-text tools for real recordings',
                'intro' => 'Choose hosted transcription in a browser or free local transcription on Windows. JERVA also supports the practical work around a first draft: progress tracking, source review, speaker grouping, online cleanup and summaries, and exports.',
                'online_button_label' => 'Start online',
                'online_button_url' => '/register',
                'desktop_button_label' => 'Download for Windows',
                'desktop_button_url' => '/download',
            ],
            'feature_visual' => [
                'subtitle' => 'JERVA transcription workflow',
                'raw_label' => 'Raw',
                'cleaned_label' => 'Cleaned',
                'export_label' => 'Export',
            ],
            'feature_rows' => [
                [
                    'eyebrow' => 'Online or offline',
                    'icon' => 'Network',
                    'title' => 'Convert audio to text in your browser or on your PC',
                    'body' => 'Use online processing when you want convenience or have limited hardware. Switch to a local Whisper model in the free Windows app when you want offline transcription.',
                    'bullets' => ['Browser-based online workspace', 'Free local Windows workflow', 'One familiar transcript workspace'],
                ],
                [
                    'eyebrow' => 'Live and uploaded audio',
                    'icon' => 'Mic',
                    'title' => 'Record live or upload a file',
                    'body' => 'Capture live speech in the workspace or bring in an existing recording. Progress and pending sections stay visible while longer audio is processed.',
                    'bullets' => ['WAV, MP3, M4A, AAC, OGG, and FLAC', 'Live microphone capture', 'Pause, retry, and progress controls'],
                ],
                [
                    'eyebrow' => 'Multilingual',
                    'icon' => 'Languages',
                    'title' => 'Transcribe speech in 99+ languages',
                    'body' => 'Multilingual Whisper models can identify and transcribe speech across more than 99 languages. Results vary by language, model, accent, background noise, and recording quality.',
                    'bullets' => ['Automatic language detection', 'Multiple Whisper model sizes', 'Translation and cleanup tools'],
                ],
                [
                    'eyebrow' => 'Smarter audio',
                    'icon' => 'FileAudio',
                    'title' => 'Skip silence and separate speakers',
                    'body' => 'Silero VAD finds spoken ranges so quiet sections do not need to be transcribed. Speaker separation groups text by detected voice when the recording supports it.',
                    'bullets' => ['Desktop voice activity detection', 'Less local Whisper work on quiet recordings', 'Detected speaker grouping'],
                ],
                [
                    'eyebrow' => 'Ready to use',
                    'icon' => 'Sparkles',
                    'title' => 'Polish, translate, and summarize',
                    'body' => 'Fix punctuation and obvious speech-to-text errors, translate a transcript, or turn a long recording into concise notes and action items.',
                    'bullets' => ['Raw text stays available', 'Custom cleanup instructions', 'Summaries from raw or polished text'],
                ],
                [
                    'eyebrow' => 'Flexible export',
                    'icon' => 'FileSpreadsheet',
                    'title' => 'Export to TXT, Word, and Excel',
                    'body' => 'Download the version you need for editing, reporting, research, publishing, or sharing with a team.',
                    'bullets' => ['Raw or cleaned transcript', 'TXT and Microsoft Word', 'Structured Excel export'],
                ],
            ],
            'comparison' => [
                'title' => 'Online and desktop transcription, compared',
                'intro' => 'Both options lead to the same JERVA workflow. Choose based on your hardware, privacy needs, and whether you want hosted processing.',
                'label_column' => 'Compare',
                'online_column' => 'Online',
                'desktop_column' => 'Windows desktop',
                'pricing_note' => 'See the current online rates and free allowance on the',
                'pricing_link_label' => 'Pricing page',
                'pricing_link_url' => '/price',
                'pricing_link_suffix' => '.',
                'rows' => [
                    ['label' => 'Setup', 'online' => 'Works in a modern browser', 'desktop' => 'Install the free Windows app and a Whisper model'],
                    ['label' => 'Cost', 'online' => 'Free daily allowance, then pay as you go', 'desktop' => 'Free local transcription'],
                    ['label' => 'Hardware', 'online' => 'Good for lightweight computers', 'desktop' => 'Speed depends on CPU, RAM, GPU, and model'],
                    ['label' => 'Audio processing', 'online' => 'Processed by hosted transcription services', 'desktop' => 'Processed locally in offline mode'],
                    ['label' => 'Account', 'online' => 'JERVA account required', 'desktop' => 'No account required for offline transcription'],
                    ['label' => 'Best for', 'online' => 'Convenience and limited local hardware', 'desktop' => 'Free, private, offline-capable transcription'],
                ],
            ],
            'faq' => [
                ['question' => 'Which Whisper model should I use?', 'answer' => 'Start with Tiny or Small on limited hardware and move to Medium, Large v3, or Turbo when you have more memory or compatible GPU resources. Larger models can improve results but take more storage and processing power.'],
                ['question' => 'Will speaker separation always identify every person correctly?', 'answer' => 'No. Speaker grouping depends on voice differences, overlapping speech, microphone quality, noise, and the recording. Treat labels as a helpful first pass and review important transcripts.'],
                ['question' => 'Can JERVA translate a transcript?', 'answer' => 'Yes. You can translate and clean transcript text with presets or custom instructions. Keep the raw transcript available so names, numbers, and important wording can be checked.'],
                ['question' => 'Where is voice activity detection available?', 'answer' => 'Silero VAD is part of the Windows desktop workflow. It finds spoken ranges before local Whisper transcription. JERVA does not currently advertise VAD as a way to reduce online billing.'],
            ],
            'faq_heading' => [
                'title' => 'Feature FAQ',
            ],
            'cta' => [
                'title' => 'Start with the workflow that suits you',
                'body' => 'Create an online account or download the free Windows app for local Whisper transcription.',
                'online_button_label' => 'Start online',
                'online_button_url' => '/register',
                'desktop_button_label' => 'Download for Windows',
                'desktop_button_url' => '/download',
            ],
            'schema' => [
                'breadcrumb_label' => 'Features',
            ],
        ],
        'download' => [
            'seo' => [
                'title' => 'Free Offline Audio to Text App for Windows | JERVA',
                'description' => 'Download JERVA for Windows to convert audio to text locally with Whisper, use VAD and speaker grouping, review the recording, and export the transcript.',
            ],
            'hero' => [
                'eyebrow' => 'Free Windows audio-to-text app',
                'title' => 'Convert audio to text offline on Windows',
                'intro' => 'Run multilingual Whisper models on your own computer without a subscription. JERVA can transcribe live or uploaded audio locally, skip silent ranges, separate detected speakers, and export finished text.',
            ],
            'download_card' => [
                'badge' => 'Free • No subscription • Offline capable',
                'title' => 'Download JERVA for Windows',
                'body' => 'The app is free. No account is required for offline transcription, and you can add optional online processing whenever local hardware is not the right fit.',
                'button_label' => 'Download free for Windows',
                'empty_label' => 'Release temporarily unavailable',
                'size_unavailable_label' => 'size unavailable',
                'date_unavailable_label' => 'date unavailable',
                'metadata_separator' => '|',
                'unavailable_body' => 'The desktop release is not available right now. Online transcription is still available.',
                'models_link_label' => 'Whisper models',
                'models_link_url' => '#models',
                'requirements_link_label' => 'System requirements',
                'requirements_link_url' => '#requirements',
            ],
            'benefits_intro' => [
                'title' => 'More than a basic Whisper window',
                'intro' => 'JERVA brings local speech recognition, audio preparation, transcript review, and useful exports into one Windows workspace.',
            ],
            'benefits' => [
                ['icon' => 'ShieldCheck', 'title' => 'Local when you want it', 'body' => 'Select offline mode to process recordings on your Windows computer instead of sending the audio to hosted transcription.'],
                ['icon' => 'Mic', 'title' => 'Live and uploaded audio', 'body' => 'Record speech directly or transcribe existing WAV, MP3, M4A, AAC, OGG, and FLAC files.'],
                ['icon' => 'Scissors', 'title' => 'Skip silent sections', 'body' => 'Silero VAD detects speech and removes quiet ranges from the transcription workload.'],
                ['icon' => 'Users', 'title' => 'Group detected speakers', 'body' => 'Speaker separation can organize transcript sections by voice when the audio is clear enough.'],
            ],
            'models' => [
                'title' => 'Choose a Whisper model for your hardware',
                'intro' => 'Model downloads are optional and managed inside the desktop app. Smaller models run with fewer resources; larger models trade more memory and storage for stronger recognition.',
                'name_column' => 'Model',
                'size_column' => 'Download',
                'best_for_column' => 'A good starting point for',
                'items' => [
                    ['name' => 'Tiny', 'size' => '42 MiB', 'best_for' => 'Fast tests and computers with limited memory'],
                    ['name' => 'Small', 'size' => '252 MiB', 'best_for' => 'A practical everyday balance of speed and quality'],
                    ['name' => 'Medium', 'size' => '785 MiB', 'best_for' => 'More demanding recordings on capable hardware'],
                    ['name' => 'Large v3', 'size' => '1.1 GiB', 'best_for' => 'Higher-quality local recognition with more resources'],
                    ['name' => 'Turbo', 'size' => '834 MiB', 'best_for' => 'Faster high-capability transcription'],
                ],
                'note' => 'Transcription speed and accuracy vary with language, model, hardware, speakers, and recording quality.',
            ],
            'requirements' => [
                ['icon' => 'Laptop', 'title' => 'Windows', 'body' => 'A current 64-bit Windows desktop or laptop. The public desktop release is Windows-only.'],
                ['icon' => 'Cpu', 'title' => '8 GB RAM recommended', 'body' => 'Smaller models use less memory. More RAM and an optional compatible GPU help larger models run smoothly.'],
                ['icon' => 'HardDrive', 'title' => 'Model storage', 'body' => 'Allow space for the app plus the models you choose, from about 42 MiB to 1.1 GiB each.'],
                ['icon' => 'ShieldCheck', 'title' => 'Internet for setup', 'body' => 'Internet is needed to download the app and a Whisper model. After that, offline transcription can run without an account.'],
            ],
            'requirements_intro' => [
                'title' => 'System requirements',
            ],
            'steps' => [
                'title' => 'Create your first offline transcript',
                'items' => [
                    ['title' => 'Install JERVA', 'body' => 'Download the current Windows package and complete the installation.'],
                    ['title' => 'Choose a model', 'body' => 'Let JERVA match a Whisper model to your available resources or select one yourself.'],
                    ['title' => 'Record or upload', 'body' => 'Use live capture or add an audio file, then review, polish, summarize, and export the result.'],
                ],
            ],
            'account' => [
                'title' => 'Online transcription is there when you need it',
                'body' => 'Sign in from the desktop app to switch to hosted processing on a lightweight computer or when you do not want to wait for a local model.',
                'bullets' => ['Offline: free local Whisper transcription', 'Online: free daily allowance and pay-as-you-go credit'],
                'button_label' => 'Create an online account',
                'button_url' => '/register',
                'pricing_link_label' => 'See current online pricing',
                'pricing_link_url' => '/price',
                'pricing_link_suffix' => 'for times when you prefer hosted processing.',
            ],
            'faq' => [
                ['question' => 'Is the Windows app completely free?', 'answer' => 'Yes. The app and offline transcription workflow are free. Optional hosted transcription uses the same free daily allowance and pay-as-you-go pricing as the browser workspace.'],
                ['question' => 'Do I need an account?', 'answer' => 'No account is required to use installed Whisper models in offline mode. An account is required only for online transcription and account-based services.'],
                ['question' => 'Will the app work without internet?', 'answer' => 'Yes, after the app and at least one Whisper model have been downloaded. Online transcription, model downloads, and account services still require internet access.'],
                ['question' => 'Does offline mode upload my recording?', 'answer' => 'No. When offline mode is selected, Whisper transcription runs on your computer. Be sure to check the selected mode before processing sensitive audio.'],
                ['question' => 'Which languages are supported?', 'answer' => 'The multilingual Whisper models used by JERVA can recognize more than 99 languages. Performance varies widely, so review important names, numbers, and quotations.'],
                ['question' => 'What if my computer is too slow?', 'answer' => 'Try a smaller Whisper model, adjust the resource settings, or sign in and use optional online processing. JERVA supports CPU fallback and can use compatible GPU resources when available.'],
            ],
            'faq_heading' => [
                'title' => 'Desktop FAQ',
            ],
            'schema' => [
                'breadcrumb_label' => 'Download',
            ],
        ],
    ],
];
