<?php

return [
    'default' => 'free',

    'tiers' => [
        'free' => [
            'name' => 'Free Daily',
            'tagline' => 'Every account gets a fresh transcription allowance each day.',
            'monthly_price' => 0,
            'yearly_price' => 0,
            'price_label' => '$0',
            'price_per_second' => 0,
            'upload_price_per_hour' => 0,
            'live_price_per_hour' => 0,
            'llm_price' => 0,
            'polish_price_per_character' => 0,
            'summary_price_per_character' => 0,
            'minutes' => 60,
            'free_polish_uses_per_day' => 3,
            'free_summary_uses_per_day' => 3,
            'polish_characters' => 0,
            'summary_characters' => 0,
            'cta' => 'Start free',
            'featured' => false,
            'features' => [
                '60 transcription minutes every day',
                'Upload audio transcription',
                'Live browser transcription',
                '3 polish and 3 summarize actions every day',
                'Export TXT, Word, and Excel files',
            ],
            'entitlements' => [
                'upload' => true,
                'live' => true,
                'polish' => true,
                'summarize' => true,
                'exports' => ['txt', 'docx', 'xlsx'],
            ],
        ],

        'payg' => [
            'name' => 'Pay as you go',
            'tagline' => 'Buy extra minutes only when you need them.',
            'monthly_price' => null,
            'yearly_price' => null,
            'price_label' => 'Pay as you go',
            'price_per_second' => 0.05277778,
            'upload_price_per_hour' => 190,
            'live_price_per_hour' => 240,
            'llm_price' => 5,
            'polish_price_per_character' => 0.0002,
            'summary_price_per_character' => 0.0002,
            'minutes' => 600,
            'free_polish_uses_per_day' => 0,
            'free_summary_uses_per_day' => 0,
            'polish_characters' => 100000,
            'summary_characters' => 100000,
            'cta' => 'Buy minutes',
            'featured' => true,
            'features' => [
                '600 transcription minutes',
                '100,000 polish characters',
                '100,000 summarize characters',
                'Added to your credit balance',
                'No recurring payment',
                'Pay only when the free daily allowance is not enough',
            ],
            'entitlements' => [
                'upload' => true,
                'live' => true,
                'polish' => true,
                'summarize' => true,
                'exports' => ['txt', 'docx', 'xlsx'],
            ],
        ],
    ],

    'comparison' => [
        '60 free minutes reset daily' => ['free', 'payg'],
        'Upload audio transcription' => ['free', 'payg'],
        'Live browser transcription' => ['free', 'payg'],
        '3 daily polish actions' => ['free', 'payg'],
        '3 daily summarize actions' => ['free', 'payg'],
        'Pay-as-you-go polish character credits' => ['payg'],
        'Pay-as-you-go summarize character credits' => ['payg'],
        'TXT export' => ['free', 'payg'],
        'Word and Excel exports' => ['free', 'payg'],
        'One-time minute credits' => ['payg'],
    ],
];
